### ISSUE TITLE
Unable to unbind from an event proxy.

### ISSUE THREAD

**Issue by furf** [flightjs/flight#281]
When binding an event proxy as such:
`this.on('click', 'foo');`

It seems that unbinding is not possible:
`this.off('click', 'foo');`

The proxied listener is an anonymous function and is not referenced in any way and is therefore unaccessible at the time off is called.

It seems that a workaround might be possible, but would require a non-trivial amount of mapping. You would probably need to consider a many-to-one relationship, as the following is possible with the existing implementation that leverages jQuery on and trigger:
`this.on('mouseover mousemove mouseout', 'eek')`

**Comment by phuu** [comment]
Hmm. After a few hours on it, I'm going to wontfix and close this. We're going to remove proxying before 2 (and move it into userland with a mixin), so I don't think it bears too much effort now.
