### ISSUE TITLE
Mixins this.after advice is not mixed in when DEBUG is true

### ISSUE THREAD

**Issue by BugiDev** [flightjs/flight#289]
I have a component which has it's own this.after advice, and then i mix in a mixin with this.after advice again. This behavior is working perfectly when i disable the DEBUG mode, but when i turn it on, I can see that the event is triggered, but the listener, which is defined and attached in mixin, is never called. Does anybody have any clue why is this the case or how to fix this issue?

**Comment by phuu** [comment]
@BugiDev is this still an issue?

Fwiw, that `var self` is going to cause you trouble because the scope it's declared in is shared by all instances of the component the mixin is added to (add some logging next to it to demonstrate how often it's run). There's almost certainly a better way.
