### ISSUE TITLE
Error when enabling Debug API (bug introduced in Flight 1.2.0?)

### ISSUE THREAD

**Issue by zeno** [flightjs/flight#300]
After upgrading to Flight 1.2.0, I get an error when trying to enable the [Debug API](https://github.com/flightjs/flight/blob/master/doc/debug_api.md) with `debug.enable(true)`. 

The error is _TypeError: Cannot assign to read only property..._ and it seems to be caused by [this line](https://github.com/flightjs/flight/blob/master/lib/debug.js#L124).

**Comment by phuu** [comment]
Hey @zeno, thanks for the report. Are you still seeing this?
