### ISSUE TITLE
Suggestion: deprecate this.$node

### ISSUE THREAD

**Issue by necolas** [flightjs/flight#302]
If there's still interest in eventually not depending on jQuery, this might be worth deprecating now as it seems to be the only place where we expose a jQuery wrapped object from the Flight API itself.

**Comment by phuu** [comment]
This is closely related to #320, and will probably be fixed by that.

**Comment by giuseppeg** [comment]
@phuu you can close this I guess

**Comment by phuu** [comment]
Yep! Woohoo.
