### ISSUE TITLE
Don't depend on jQuery

### ISSUE THREAD

**Issue by hwclass** [flightjs/flight#320]
Hi the creators of Flightjs,

This is just a recommendation. Do you have any idea to avoid the dependency over jQuery and make a build of Flightjs without it?

Thanks.

**Comment by panesofglass** [comment]
:+1:

**Comment by phuu** [comment]
WIP is on the [feature/remove-jquery-320](https://github.com/flightjs/flight/tree/feature/remove-jquery-320) branch.

**Comment by tunderdomb** [comment]
+1
I'd really love to see a lightweight version without the dependency too. 

Also, out of curiosity, why did you decide to make it a requirement in the first place? I mean I can see this framework stand on its own without it just fine. Thanks!

**Comment by phuu** [comment]
So this is actually kinda done. v2 isn't ready to use yet, but as of recently it doesn't use jQuery! Woo!

[This issue](https://github.com/flightjs/flight-toolbox/issues/2) on the flight-toolbox will track adding jQuery back if you want it, via a dom plugin replacement of some kind. The specifics of that are yet to be worked out.
