### ISSUE TITLE
Drop defaultAttrs

### ISSUE THREAD

**Issue by phuu** [flightjs/flight#328]
API breaking change.

The interaction between `attributes` and `defaultAttrs` is unclear and open to hard-to-spot bugs, for example when a mixin uses the a different form to the component.

Support for `defaultAttrs` should be dropped, breaking the API and forcing everyone to move the `attributes`.

**Comment by phuu** [comment]
Thinking this could be done by making attributes and defaultAttrs compatible (currently they're mutually exclusive).

**Comment by giuseppeg** [comment]
Yeah we could have a flag on `attributes` say `strictmode` to disable the strict checks introduced by this method. In this way `defaultAttrs` would only be a proxy fn to `attributes` with `strictmode: false`

**Comment by phuu** [comment]
Enough time has passed for `defaultAttrs` to have been migrated away from, so the deprecation strategy will be:

- release a `1.x` that spits warnings (in debug mode) when `defaultAttrs` is used
- make defaultAttrs a warning-spitting (regardless of debug mode) no-op in `2`

We need to be this strict about it because the two are mutually exclusive, so projects like TweetDeck will have to do an all-at-once switch.
