### ISSUE TITLE
Remove event proxying from core

### ISSUE THREAD

**Issue by phuu** [flightjs/flight#332]
Event proxying added complexity to Flight core and should have been done in userland with a mixin. `2` will remove it. `1.x` will continue to support it.

We'll publish a mixin that adds this, probably as `this.(un)proxy`.

**Comment by phuu** [comment]
Landed in 1f3203d, but we also need a mixin the add this back via the API discussed above.

**Comment by phuu** [comment]
I've submitted an issue on the new [flight-toolbox](https://github.com/flightjs/flight-toolbox) repo to track the creation of this mixin: https://github.com/flightjs/flight-toolbox/issues/1

**Comment by giuseppeg** [comment]
flight-toolbox++
