### ISSUE TITLE
Update README to mention flight-toolbox

### ISSUE THREAD

**Issue by phuu** [flightjs/flight#337]
[The toolbox](https://github.com/flightjs/flight-toolbox) will be the canonical resource for mixins and the blessed Flight stack, so we should mention it in the README.

**Comment by marti1125** [comment]
@phuu Could I help with this?

**Comment by phuu** [comment]
@marti1125 Sure! Just a link and bit of text would be perfect — thanks :smile:

**Comment by marti1125** [comment]
@phuu excuse me. Is it https://github.com/flightjs/flight/blob/master/README.md or https://github.com/flightjs/flight/tree/master/doc

**Comment by phuu** [comment]
@marti1125 Ooh, good question. I think the first one, but I'll have a think about how we can integrate this stuff into the main documentation.

**Comment by marti1125** [comment]
@phuu maybe in https://github.com/flightjs/flight/blob/master/doc/mixin_api.md I am waiting of your instructions for help in this issue :)
