### ISSUE TITLE
Typo and slightly confusing note

### ISSUE THREAD

**Issue by paulwib** [flightjs/flight#338]
> Note: work is currently ongoing for Flight v2 and beyond, which will make some backward incompatibile changes. To see the latest v1.x code and documentation, check out the barnch.

`s/barnch/branch/`

So is the v2 dev happening on master? I was confused as there is a v.2.0.0-dev branch too.

**Comment by paulwib** [comment]
Also `s/incompatibile/incompatible/` ;)

**Comment by phuu** [comment]
Hey @paulwib — thanks for reporting these, I'll fix them right away.

Yes, v2 is happening on master — I'll delete the v2 branch too.
