### ISSUE TITLE
Virtual DOM Support

### ISSUE THREAD

**Issue by crudbug** [flightjs/flight#345]
I observed the hard jQuery requirement can be made optional with the ongoing work on 2.0. Decoupling DOM layer from flightjs will enable pluggable DOM management backends. 

How difficult will be support add v-dom support ? 

-Alan

**Comment by phuu** [comment]
Hey @crudbug.

I think virtual-dom is usable already, although I've not tried it myself. I see no problem with a component rendering itself with virtual-dom, and just not using the jQuery-based features, but I don't know how it would work in a large component tree.

If you experiment with this, please report back! I'll be really interested to hear how you get on.

**Comment by phuu** [comment]
Looks unlikely this going to go anywhere in Flight core. User-land may provide support.
