### ISSUE TITLE
Suggestion: Internal cache for this.select() vs. repeatedly find

### ISSUE THREAD

**Issue by fridays** [flightjs/flight#351]
Hi everybody, I am just getting started with flight and love its simplicity. I am used to cache all jQuery objects for later reuse, so jQuery only has to query the DOM once when finding an element.

Flights `this.select()` method uses jQuerys find method in every call:
```javascript
this.select = function(attributeKey) {
    return this.$node.find(this.attr[attributeKey]);
};
```
Wouldn't it make sense to store the result in an internal cache and only use `find` again when we expect the DOM to have been changed? Something like this: 
```javascript
this.select = function(attributeKey, forceFindAgain) {
    if (!this.someCache[attributeKey] || forceFindAgain) {
        this.someCache[attributeKey] = this.$node.find(this.attr[attributeKey]);
    }
    return this.someCache[attributeKey];
};

// Find from DOM, next time from cache:
this.select(something);

// Force requery of the DOM:
this.select(something, true);
```
Here is a jsperf to demonstrate the difference in repeatedly using `find` vs using a cached jQuery object: http://jsperf.com/jquery-find-again-vs-cached-results

Does this make any sense?

**Comment by phuu** [comment]
Hey @fridays — thanks for this! Unfortunately, making an optimisation like this would only work if the DOM under a component was static — if the set of nodes that matched the selector changes, a cached version would miss these changes. The boolean flag is useful, but the assumption in existing code is that select is dynamic, so this would be a significant breaking change.

You could however make a (really useful) mixin called something like `withSelectCached` that added a method exactly like you describe (perhaps `this.selectCached`) that helps in the case that you *know* the DOM is static.
