### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by phillip-haydon** [flightjs/flight#353]
Can we get the documentation viewable somewhere? The flight website links to the readme. 

The GH Wiki allows the community to contribute easily... And you can have menus and such to make navigation easy...

**Comment by fridays** [comment]
I like this idea.

**Comment by phuu** [comment]
Hey! I'd love to see an updated, modern Flight website with full documentation and examples. It's just a case of when we'll have time to work on it!

**Comment by phillip-haydon** [comment]
@phuu I would like to learn flight.js but there's no real doco, which is why I suggested using the Wiki, atleast then its easy for the community to contribute to the doco so it takes the burden off you.

Maybe 60% of the doco for Nancy framework isn't written by us, its written by the community. Any errors always corrected by the community.

Working examples can be linked to jsfiddle or similar.

**Comment by taveras** [comment]
Have to agree with @phillip-haydon and @phuu, when I first read about flight it sounds like a delight. The [README](https://github.com/flightjs/flight/blob/v1.x/README.md) and the [API Documentation](https://github.com/flightjs/flight/blob/v1.x/doc/README.md) are great resources. But a web page with more literature and examples would be awesome!

**Comment by jkup** [comment]
I'd love to help on adding documentation / building out a modern website. Should we have a different repo for this?

**Comment by phuu** [comment]
Cool! My approach would be to keep the docs in the same repo as the code and use a build task to commit them in website form to a `gh-pages` branch.

The build-step approach might be wrong but I think it's important to keep the docs beside the code, so commits can contain both and be checked for consistency.

**Comment by giuseppeg** [comment]
@phuu I'd say lets improve the current docs first, maybe starting by adding more examples. We can turn them into a Jekyll site in no time later.

Good examples could be:
* managing the lifecycle of a group of components in a page
* PJAX-ing with flight
* integration with Boostrap
In general FAQ kind of articles.

**Comment by phillip-haydon** [comment]
All this needs is for @phuu to open the Wiki so we can contribute to it.

But this has taken too long I've lost interest in helping now. Will move on to another framework. I'll leave this open for you but I'm unsubscribing.

**Comment by giuseppeg** [comment]
@phillip-haydon I am ok with that although I think that keeping the docs in the same repo is better for a simple reason: when you tag a new release the docs reflect that version state.

Also people can contribute with pull requests already, although that's not as straightforward as editing a wiki :)

**Comment by phuu** [comment]
The documentation is OK for what we have now — there's unlikely to be any more core Flight development, so going to close this for now.
