### ISSUE TITLE
The link to the documentation takes you to README.md

### ISSUE THREAD

**Issue by jvennix-rmn** [flightjs/flight#360]
On the website http://flightjs.github.io/, clicking the link "The project includes full documentation" takes you to the README on master, which has no mention of documentation. A link to https://github.com/flightjs/flight/tree/master/doc would be more helpful.

**Comment by jkup** [comment]
Added a PR on the flight site repo: https://github.com/flightjs/flightjs.github.io/pull/15

**Comment by jvennix-rmn** [comment]
Ah! I was looking for a gh-pages branch, I forgot the site is on a different repo. Thanks @jkup !
