### ISSUE TITLE
Can't listen/trigger events on the `window` object

### ISSUE THREAD

**Issue by giuseppeg** [flightjs/flight#368]
`dom.select` and `dom.selectAll` check for `selector.nodeType` which is `undefined` for the `window` object. This makes listening/triggering events on the `window` impossible.

In addition to that there is a bug in [`trigger`](https://github.com/flightjs/flight/blob/master/lib/base.js#L104).
When triggering with an event object `element` ends up being `this.node` and `event` = `selector/node`
Tests aren't failing because we assume that the first parameter is a string e.g. `document`, however if you try to trigger on an actual dom element it fails.

**Comment by phuu** [comment]
v2 thing — closing.
