### ISSUE TITLE
Why not under active development?

### ISSUE THREAD

**Issue by elgalu** [flightjs/flight#377]
Can you clarify in the README why is not under active development? what happened, what changed, is there something better? can you link it ;) what are you using instead?

thanks!

**Comment by giuseppeg** [comment]
The framework is fairly mature and stable. 

In the meantime new frameworks came up with excellent ideas eg. declarative UIs, vdom and many others - @phuu [wrote about this](https://phuu.net/2016/09/26/flight-in-2016.html) recently. Implementing those into flight in my opinion would mean write a new and totally different framework.

While I still love Flight, I think that the declarative UI and mono directional data flow pattern of React is a bit more practical and efficient.

**Comment by elgalu** [comment]
Cool, thanks for clarifying plus great post link
