### ISSUE TITLE
Passing jQuery object as data argument to this.trigger in debug mode fails

### ISSUE THREAD

**Issue by alex-seville** [flightjs/flight#38]
While in debug mode, `trigger` attempts a `window.postMessage` with the data argument of the trigger call.  If this data is a jQuery object, the call (sometimes, maybe always?) fails because the object is not serializable into JSON.

However, the [jQuery trigger method](https://github.com/jquery/jquery/blob/master/src/event.js#L201) can take jQuery objects as data, and if I disable debug mode it works in Flight as well.

The relevant line is here: https://github.com/twitter/flight/blob/master/lib/component.js#L70

I would have submitted a PR but I'm not sure the best way to handle this situation (maybe check if `data instanceof jquery` and don't throw an error if it is?).

**Comment by traviskaufman** [comment]
can't pass [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData) either, making decoupling data and ui for a "File Upload" component pretty tricky
